import { Property } from './property';
import { STATUS, STATE } from './property';

export const PROPERTIES: Property[] = [
  {
    id: 1,
    name: 'Dell Arvuti',
    last_check: new Date('2020-02-16'),
    room: 'U03-304',
    status: STATUS.checked,
    state: STATE.not_in_use,
    description: 'Dell arvuti',
  },
  {
    id: 2,
    name: 'Projektor',
    last_check: new Date('2019-12-12'),
    room: 'U06-201',
    status: STATUS.checked,
    state: STATE.inuse,
    description: 'xxx',
  },
  {
    id: 3,
    name: 'Laud',
    last_check: new Date('2019-01-30'),
    room: 'U03-304',
    status: STATUS.checked,
    state: STATE.in_repair,
    description: 'xxx',
  },
  {
    id: 4,
    name: 'Laud',
    last_check: new Date('2018-04-06'),
    room: 'U03-304',
    status: STATUS.checked,
    state: STATE.need_repair,
    description: 'xxx',
  },
  {
    id: 5,
    name: 'iPad',
    last_check: new Date('2017-12-04'),
    room: 'U04-304',
    status: STATUS.unchecked,
    state: STATE.unknown,
    description: 'xxx',
  },
  {
    id: 6,
    name: 'Server',
    last_check: new Date('2021-01-19'),
    room: 'U06-100',
    status: STATUS.checked,
    state: STATE.inuse,
    description: 'xxx',
  },
  {
    id: 7,
    name: 'Mikroskoop',
    last_check: new Date('2019-12-01'),
    room: 'U02-304',
    status: STATUS.checked,
    state: STATE.in_repair,
    description: 'xxx',
  },
  {
    id: 8,
    name: 'Klaviatuur',
    last_check: new Date('2020-12-03'),
    room: 'U03-304',
    status: STATUS.checked,
    state: STATE.inuse,
    description: 'xxx',
  },
];
